from __future__ import annotations


DEFAULT_CHROMA_HOST = "api.trychroma.com"
DEFAULT_CHROMA_TENANT = "7017286c-bbfb-415f-b058-2b37f136fe70"
DEFAULT_CHROMA_DATABASE = "diplomski"
DEFAULT_COLLECTION_NAME = "diplomski_rag"
DEFAULT_CHROMA_SPARSE_KEY = "sparse_embedding"
DEFAULT_CHROMA_DOCUMENT_MAX_BYTES = 16 * 1024
DEFAULT_CHROMA_STORE_BATCH_SIZE = 16

DEFAULT_CHUNK_MAX_CHARACTERS = 1000
DEFAULT_CHUNK_OVERLAP = 200

DEFAULT_CHROMA_QWEN_TASK = "retrieval"
DEFAULT_HYBRID_DENSE_WEIGHT = 0.7
DEFAULT_HYBRID_SPARSE_WEIGHT = 0.3
DEFAULT_GROUP_BY_DOCUMENT_LIMIT = 2

DEFAULT_GEMINI_MODEL = "gemini-3.6-flash"
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 12000

DEFAULT_TOP_K = 5
DEFAULT_RETRIEVAL_CANDIDATE_POOL_SIZE = 60
DEFAULT_MAX_CONTEXT_CHARS = 14000
