from __future__ import annotations


DEFAULT_CHROMA_DIR = "chroma_db"
DEFAULT_COLLECTION_NAME = "diplomski_rag"

DEFAULT_EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-0.6B"
DEFAULT_EMBEDDING_DEVICE = "auto"
DEFAULT_EMBEDDING_BATCH_SIZE = 1
DEFAULT_EMBEDDING_MAX_SEQ_LENGTH = 256

DEFAULT_GEMINI_MODEL = "gemini-3.6-flash"
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 12000

DEFAULT_TOP_K = 5
DEFAULT_RETRIEVAL_CANDIDATE_POOL_SIZE = 60
DEFAULT_MAX_CONTEXT_CHARS = 14000
